In [168]:
a = open('010 rosalind_cons.txt', 'r').read()

In [169]:
b = a.replace('\n', '').split('>')[1:]
sequences=[]
for i in b:
    seq = i[13:]
    sequences.append(seq)

In [170]:
import pandas as pd

In [171]:
s = []
for i in sequences:
    s.append(list(i))
    
df = pd.DataFrame(s)

In [172]:
df

,0,1,2,3,4,5,6,7,8,9,...,935,936,937,938,939,940,941,942,943,944
0,A,C,C,T,A,A,C,G,C,C,...,T,A,T,C,C,T,C,C,G,G
1,G,C,G,A,T,A,C,G,G,G,...,T,G,G,C,A,A,C,A,G,G
2,G,G,A,T,A,C,T,A,C,T,...,A,A,C,C,G,C,T,G,G,G
3,C,A,C,T,T,A,C,G,C,C,...,T,C,T,G,T,T,A,G,T,T
4,A,A,C,A,C,A,T,G,A,C,...,C,C,C,A,A,T,T,C,A,C
5,G,G,G,G,G,A,A,A,A,A,...,C,G,A,T,T,A,C,A,A,G
6,T,G,T,A,T,G,C,C,C,C,...,T,G,A,A,A,C,A,T,G,G
7,G,T,A,G,G,C,A,G,C,A,...,A,T,T,C,A,G,G,G,T,G
8,C,C,A,C,G,A,C,A,C,A,...,C,T,T,A,G,T,C,G,A,A
9,C,A,C,A,A,A,T,G,C,C,...,C,A,C,A,A,T,A,C,G,A

In [173]:
counts = pd.DataFrame(columns = ['A', 'C', 'G', 'T'])
consensus = ''

for i in df:
    counts=counts.append(df[i].value_counts())
    consensus += (df[i].value_counts().idxmax())

counts=counts.fillna(0).astype(int)

In [174]:
print(consensus)
print(counts.T)

GCCATACGCCGAGCTCTTAGATGTATTGGAGAAGCTCGGTGTTGACTACATCTGGTATATCCTCGTGGGCTTTCCCCGGGGAATATCCTGTATCTGTGGCACATGGGACTAAGTACATAGAGGGCTTCGCTCCTCCTCGTTGCCGAATGGAGTCGCCTTCCTATGAACCGTAAGCCATACCTCTATCCTGTTCCGTCACCATTGTCCCCCGTTACCGTACATCCCAAATTTAGCAGGGCTGGCCCGCTGCACCTGTTAGCACTCTCTTACGTTGTTCCCCTAGCTGCTAGTCAACTAAAATCGGGTGGCTGCCCGCATGATTCCGGAATTGTGGCGCTCATAGTCGGTGGGTTTTATACTCTAGCGGCACATCGGAGGTGGTCTCCACAGTCACGAAAGCCCCCTGTTAATTTTTACAATTTCCTTAATGTCCTTCCCGTGTTTCTCGATTGCTGGTGGCAGACGCGTCCCGTACATATCATTCCATACTGGGGTAACGAACCACCGTAGGGTCCCTGTTTCAGCGAGCCGCACGTTCCGAATCGAGTGCTTCCGCACGACCTGCCAGTCAATAGCTGACAGTTCCTACCATGAGACTTCAAGTTCCTGACGTACGATGGTGATGACTGCTTTCATCTTGCCGAGCTTCGAAATTCTATACAGGTGGGCTGTTTGCGTGTAGAGAATGTCTAGGCGCGGGAACCCGTCACCGTATTGCGCTTCGGGCCGCCTCCGACGTAGCGAAGACCTCTTCGTAGTCCCTATGGGTAGTACCGGGATTTCTTTTCTCAAGACTTGGTGGAATCGACCGTGGTTTGTACAGCGAGGCATTTGGCGGCACCTGCTCTCGGTTCCATCTGGGGATTTCACAACCGAGAAGACTGCCTCCAACTCACCCTGGTAGCTATCATCTGGCGAATGAGGCATTGGATACTTGTCATCGGG
   0    1    2    3    4    5    6    7    8    9    ...  935  936  937  938  \
A    2    3    3    4    3    7    2    3    2    3  ...    2    3    2    4
C    3    3    4    1    1    2    5    1    7    5  ...    4    2    3    4
G    4    3    2    2    3    1    0    6    1    1  ...    0    3    1    1
T    1    1    1    3    3    0    3    0    0    1  ...    4    2    4    1

   939  940  941  942  943  944
A    5    2    3    2    3    2
C    1    2    4    3    0    1
G    2    1    1    4    5    6
T    2    5    2    1    2    1

[4 rows x 945 columns]

In [175]:
with open('010 output.txt', 'a') as f:
    dfAsString = counts.T.to_string(header=False, index=True)
    f.write(dfAsString)